@startuml
class Modelo.Productos {
- int id
- String codigo
- String nombre
- String proveedor
- int stock
- double precio
+ int getId()
+ void setId(int)
+ String getCodigo()
+ void setCodigo(String)
+ String getNombre()
+ void setNombre(String)
+ String getProveedor()
+ void setProveedor(String)
+ int getStock()
+ void setStock(int)
+ double getPrecio()
+ void setPrecio(double)
}
class Modelo.ProductosDAO {
~ Connection con
~ conexion cn
~ PreparedStatement ps
~ ResultSet rs
+ boolean RegistrarProductos(Productos)
+ void ConsultarProveedor(JComboBox)
+ List ListarProductos()
+ boolean EliminarProducto(int)
+ boolean ModificarProductos(Productos)
+ Productos BuscarPro(String)
+ Config BuscarDatos()
+ boolean ModificarDatos(Config)
}
class Reportes.Excel {
+ {static} void reporte()
}
class Modelo.Config {
- int id
- int ruc
- String nombre
- int telefono
- String direccion
- String razon
+ int getId()
+ void setId(int)
+ int getRuc()
+ void setRuc(int)
+ String getNombre()
+ void setNombre(String)
+ int getTelefono()
+ void setTelefono(int)
+ String getDireccion()
+ void setDireccion(String)
+ String getRazon()
+ void setRazon(String)
}
class Frames.Registro {
~ login lg
~ loginDAO login
- javax.swing.JComboBox<String> cbxRol
- javax.swing.JButton jButton1
- javax.swing.JButton jButton2
- javax.swing.JLabel jLabel1
- javax.swing.JLabel jLabel2
- javax.swing.JLabel jLabel3
- javax.swing.JLabel jLabel4
- javax.swing.JLabel jLabel5
- javax.swing.JLabel jLabel6
- javax.swing.JLabel jLabel7
- javax.swing.JPanel jPanel1
- javax.swing.JPanel jPanel2
- javax.swing.JPanel jPanel3
- javax.swing.JPanel jPanel4
- javax.swing.JPasswordField txtContrasena
- javax.swing.JTextField txtCorreo
- javax.swing.JTextField txtNombre
+ void validar()
- void initComponents()
- void jButton2ActionPerformed(java.awt.event.ActionEvent)
- void jButton1ActionPerformed(java.awt.event.ActionEvent)
+ {static} void main(String[])
}
class Modelo.Cliente {
- int id
- int dni
- String nombre
- int telefono
- String direccion
- String razon
+ int getId()
+ void setId(int)
+ int getDni()
+ void setDni(int)
+ String getNombre()
+ void setNombre(String)
+ int getTelefono()
+ void setTelefono(int)
+ String getDireccion()
+ void setDireccion(String)
+ String getRazon()
+ void setRazon(String)
}
class Modelo.login {
- int id
- String nombre
- String correo
- String pass
- String rol
+ int getId()
+ void setId(int)
+ String getNombre()
+ void setNombre(String)
+ String getCorreo()
+ void setCorreo(String)
+ String getPass()
+ void setPass(String)
+ String getRol()
+ void setRol(String)
}
class Modelo.conexion {
~ Connection con
+ Connection getConnection()
}
class Modelo.loginDAO {
~ Connection con
~ PreparedStatement ps
~ ResultSet rs
~ conexion cn
+ login log(String,String)
+ boolean Registrar(login)
}
class Modelo.ProveedorDAO {
~ Connection con
~ conexion cn
~ PreparedStatement ps
~ ResultSet rs
+ boolean RegistrarProveedor(Proveedor)
+ List ListarProveedor()
+ boolean EliminarProveedor(int)
+ boolean ModificarProveedor(Proveedor)
}
class Modelo.Eventos {
+ void textKeyPress(KeyEvent)
+ void numberKeyPress(KeyEvent)
+ void numberDecimalKeyPress(KeyEvent,JTextField)
}
class Modelo.ClienteDAO {
~ conexion cn
~ Connection con
~ PreparedStatement ps
~ ResultSet rs
+ boolean RegistrarCliente(Cliente)
+ List ListarCliente()
+ boolean EliminarCLiente(int)
+ boolean ModificarCliente(Cliente)
+ Cliente BuscarCliente(int)
}
class Modelo.Proveedor {
- int id
- int ruc
- String nombre
- int telefono
- String direcion
- String razon
+ int getId()
+ void setId(int)
+ int getRuc()
+ void setRuc(int)
+ String getNombre()
+ void setNombre(String)
+ int getTelefono()
+ void setTelefono(int)
+ String getDirecion()
+ void setDirecion(String)
+ String getRazon()
+ void setRazon(String)
}
class Modelo.Detalle {
- int id
- String cod_pro
- int cantidad
- double precio
- int id_venta
+ int getId()
+ void setId(int)
+ String getCod_pro()
+ void setCod_pro(String)
+ int getCantidad()
+ void setCantidad(int)
+ double getPrecio()
+ void setPrecio(double)
+ int getId_venta()
+ void setId_venta(int)
}
class Modelo.Venta {
- int id
- String cliente
- String vendedor
- double total
- String fecha
+ String getFecha()
+ void setFecha(String)
+ int getId()
+ void setId(int)
+ String getCliente()
+ void setCliente(String)
+ String getVendedor()
+ void setVendedor(String)
+ double getTotal()
+ void setTotal(double)
}
class Reportes.Grafico {
+ {static} void Graficar(String)
}
class Modelo.VentaDao {
~ Connection con
~ conexion cn
~ PreparedStatement ps
~ ResultSet rs
~ int r
+ int idVenta()
+ int RegistrarVenta(Venta)
+ int RegistrarDetalle(Detalle)
+ boolean ActualizarStock(int,String)
+ List Listarventas()
}
class Frames.Loging {
~ login lg
~ loginDAO login
- javax.swing.JButton jButton1
- javax.swing.JButton jButton2
- javax.swing.JLabel jLabel1
- javax.swing.JLabel jLabel2
- javax.swing.JLabel jLabel3
- javax.swing.JLabel jLabel4
- javax.swing.JLabel jLabel6
- javax.swing.JPanel jPanel1
- javax.swing.JPanel jPanel2
- javax.swing.JPanel jPanel3
- javax.swing.JPanel jPanel4
- javax.swing.JPasswordField txtContrasena
- javax.swing.JTextField txtCorreo
+ void validar()
- void initComponents()
- void jButton2ActionPerformed(java.awt.event.ActionEvent)
- void jButton1ActionPerformed(java.awt.event.ActionEvent)
+ {static} void main(String[])
}
class Frames.Sistema {
~ Date fechaVenta
~ String fechaActual
~ Cliente cl
~ ClienteDAO client
~ Proveedor pr
~ ProveedorDAO prDao
~ Productos pro
~ ProductosDAO proDao
~ Venta v
~ VentaDao Vdao
~ Detalle Dv
~ Config conf
~ Eventos event
~ DefaultTableModel modelo
~ DefaultTableModel tmp
~ int item
~ double Totalpagar
- javax.swing.JLabel LabelVendedor
- com.toedter.calendar.JDateChooser Midate
- javax.swing.JTable TableVenta
- javax.swing.JButton btnActualizarConfig
- javax.swing.JButton btnClientes
- javax.swing.JButton btnConfig
- javax.swing.JButton btnEditarProduct
- javax.swing.JButton btnEditarProveedor
- javax.swing.JButton btnEliminarCliente
- javax.swing.JButton btnEliminarProduct
- javax.swing.JButton btnEliminarVenta
- javax.swing.JButton btnExcelProduct
- javax.swing.JButton btnGenerarVenta
- javax.swing.JButton btnGraficar
- javax.swing.JButton btnGuardarCliente
- javax.swing.JButton btnGuardarProduct
- javax.swing.JButton btnGuardarProveedor
- javax.swing.JButton btnNuevaVenta
- javax.swing.JButton btnNuevoProduct
- javax.swing.JButton btnNuevoProveedor
- javax.swing.JButton btnPDFVentas
- javax.swing.JButton btnProductos
- javax.swing.JButton btnProovedor
- javax.swing.JButton btnVentas
- javax.swing.JComboBox<String> cbxProveedorPro
- javax.swing.JButton jButton1
- javax.swing.JLabel jLabel1
- javax.swing.JLabel jLabel10
- javax.swing.JLabel jLabel11
- javax.swing.JLabel jLabel12
- javax.swing.JLabel jLabel13
- javax.swing.JLabel jLabel14
- javax.swing.JLabel jLabel15
- javax.swing.JLabel jLabel16
- javax.swing.JLabel jLabel17
- javax.swing.JLabel jLabel19
- javax.swing.JLabel jLabel20
- javax.swing.JLabel jLabel21
- javax.swing.JLabel jLabel22
- javax.swing.JLabel jLabel23
- javax.swing.JLabel jLabel24
- javax.swing.JLabel jLabel25
- javax.swing.JLabel jLabel26
- javax.swing.JLabel jLabel27
- javax.swing.JLabel jLabel28
- javax.swing.JLabel jLabel29
- javax.swing.JLabel jLabel30
- javax.swing.JLabel jLabel31
- javax.swing.JLabel jLabel32
- javax.swing.JLabel jLabel33
- javax.swing.JLabel jLabel34
- javax.swing.JLabel jLabel35
- javax.swing.JLabel jLabel36
- javax.swing.JLabel jLabel37
- javax.swing.JLabel jLabel38
- javax.swing.JLabel jLabel39
- javax.swing.JPanel jPanel1
- javax.swing.JPanel jPanel2
- javax.swing.JPanel jPanel3
- javax.swing.JPanel jPanel4
- javax.swing.JPanel jPanel5
- javax.swing.JPanel jPanel6
- javax.swing.JPanel jPanel7
- javax.swing.JPanel jPanel8
- javax.swing.JScrollPane jScrollPane2
- javax.swing.JScrollPane jScrollPane3
- javax.swing.JScrollPane jScrollPane4
- javax.swing.JScrollPane jScrollPane5
- javax.swing.JScrollPane jScrollPane6
- javax.swing.JTabbedPane jTabbedPane1
- javax.swing.JTextField jTextField1
- javax.swing.JLabel labelTotal
- javax.swing.JTable tableCliente
- javax.swing.JTable tableProducto
- javax.swing.JTable tableProveedor
- javax.swing.JTable tableVentas
- javax.swing.JButton tbnEditarCliente
- javax.swing.JButton tbnEliminarProveedor
- javax.swing.JButton tbnNuevoCliente
- javax.swing.JTextField txtCantidadProduct
- javax.swing.JTextField txtCantidadVenta
- javax.swing.JTextField txtCodigoProducto
- javax.swing.JTextField txtCodigoVenta
- javax.swing.JTextField txtDNICliente
- javax.swing.JTextField txtDescripcionProduct
- javax.swing.JTextField txtDescripcionVenta
- javax.swing.JTextField txtDireccionCLiente
- javax.swing.JTextField txtDireccionConfig
- javax.swing.JTextField txtDireccionProveedor
- javax.swing.JTextField txtDirecciónClienteVenta
- javax.swing.JTextField txtIDCliente
- javax.swing.JTextField txtIDPro
- javax.swing.JTextField txtIDProduct
- javax.swing.JTextField txtIDProveedor
- javax.swing.JTextField txtIDVenta
- javax.swing.JTextField txtIdConfig
- javax.swing.JTextField txtNombreCliente
- javax.swing.JTextField txtNombreClienteVenta
- javax.swing.JTextField txtNombreConfig
- javax.swing.JTextField txtNombreProveedor
- javax.swing.JTextField txtPrecioProduct
- javax.swing.JTextField txtPrecioVenta
- javax.swing.JTextField txtRazonCliente
- javax.swing.JTextField txtRazonClienteVenta
- javax.swing.JTextField txtRazonConfig
- javax.swing.JTextField txtRazonProveedor
- javax.swing.JTextField txtRucConfig
- javax.swing.JTextField txtRucProveedor
- javax.swing.JTextField txtRucVenta
- javax.swing.JTextField txtStockDisponible
- javax.swing.JTextField txtTelefonoCLiente
- javax.swing.JTextField txtTelefonoClienteVenta
- javax.swing.JTextField txtTelefonoConfig
- javax.swing.JTextField txtTelefonoProveedor
+ void ListarCliente()
+ void ListarProveedor()
+ void ListarProductos()
+ void ListarConfig()
+ void ListarVentas()
+ void LimpiarTable()
- void initComponents()
- void btnClientesActionPerformed(java.awt.event.ActionEvent)
- void btnProovedorActionPerformed(java.awt.event.ActionEvent)
- void cbxProveedorProActionPerformed(java.awt.event.ActionEvent)
- void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent)
- void tableClienteMouseClicked(java.awt.event.MouseEvent)
- void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent)
- void TableVentaMouseClicked(java.awt.event.MouseEvent)
- void tbnEditarClienteActionPerformed(java.awt.event.ActionEvent)
- void tbnNuevoClienteActionPerformed(java.awt.event.ActionEvent)
- void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent)
- void tableProveedorMouseClicked(java.awt.event.MouseEvent)
- void tbnEliminarProveedorActionPerformed(java.awt.event.ActionEvent)
- void btnEditarProveedorActionPerformed(java.awt.event.ActionEvent)
- void btnNuevoProveedorActionPerformed(java.awt.event.ActionEvent)
- void btnGuardarProductActionPerformed(java.awt.event.ActionEvent)
- void btnProductosActionPerformed(java.awt.event.ActionEvent)
- void tableProductoMouseClicked(java.awt.event.MouseEvent)
- void btnEliminarProductActionPerformed(java.awt.event.ActionEvent)
- void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent)
- void btnEditarProductActionPerformed(java.awt.event.ActionEvent)
- void btnNuevoProductActionPerformed(java.awt.event.ActionEvent)
- void btnExcelProductActionPerformed(java.awt.event.ActionEvent)
- void txtCodigoVentaKeyPressed(java.awt.event.KeyEvent)
- void txtCantidadVentaKeyPressed(java.awt.event.KeyEvent)
- void btnEliminarVentaActionPerformed(java.awt.event.ActionEvent)
- void txtRucVentaKeyPressed(java.awt.event.KeyEvent)
- void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent)
- void txtIdConfigActionPerformed(java.awt.event.ActionEvent)
- void txtDireccionConfigActionPerformed(java.awt.event.ActionEvent)
- void txtDescripcionVentaActionPerformed(java.awt.event.ActionEvent)
- void txtRucConfigActionPerformed(java.awt.event.ActionEvent)
- void txtTelefonoConfigActionPerformed(java.awt.event.ActionEvent)
- void txtNombreConfigActionPerformed(java.awt.event.ActionEvent)
- void txtCodigoVentaKeyTyped(java.awt.event.KeyEvent)
- void txtDescripcionVentaKeyTyped(java.awt.event.KeyEvent)
- void txtCantidadVentaKeyTyped(java.awt.event.KeyEvent)
- void txtPrecioVentaKeyTyped(java.awt.event.KeyEvent)
- void txtRucVentaKeyTyped(java.awt.event.KeyEvent)
- void txtNombreClienteVentaKeyTyped(java.awt.event.KeyEvent)
- void txtPrecioProductKeyTyped(java.awt.event.KeyEvent)
- void txtDNIClienteKeyTyped(java.awt.event.KeyEvent)
- void txtNombreClienteActionPerformed(java.awt.event.ActionEvent)
- void txtTelefonoCLienteActionPerformed(java.awt.event.ActionEvent)
- void txtDireccionCLienteKeyTyped(java.awt.event.KeyEvent)
- void txtNombreClienteKeyTyped(java.awt.event.KeyEvent)
- void txtTelefonoCLienteKeyTyped(java.awt.event.KeyEvent)
- void txtRazonClienteKeyTyped(java.awt.event.KeyEvent)
- void txtRucProveedorKeyTyped(java.awt.event.KeyEvent)
- void txtNombreProveedorKeyTyped(java.awt.event.KeyEvent)
- void txtTelefonoProveedorKeyTyped(java.awt.event.KeyEvent)
- void txtDireccionProveedorKeyTyped(java.awt.event.KeyEvent)
- void txtRazonProveedorKeyTyped(java.awt.event.KeyEvent)
- void txtCodigoProductoKeyPressed(java.awt.event.KeyEvent)
- void txtCodigoProductoKeyTyped(java.awt.event.KeyEvent)
- void txtDescripcionProductKeyTyped(java.awt.event.KeyEvent)
- void txtCantidadProductKeyTyped(java.awt.event.KeyEvent)
- void txtRucConfigKeyTyped(java.awt.event.KeyEvent)
- void txtNombreConfigKeyTyped(java.awt.event.KeyEvent)
- void txtTelefonoConfigKeyTyped(java.awt.event.KeyEvent)
- void txtDireccionConfigKeyTyped(java.awt.event.KeyEvent)
- void txtRazonConfigKeyTyped(java.awt.event.KeyEvent)
- void btnActualizarConfigActionPerformed(java.awt.event.ActionEvent)
- void btnConfigActionPerformed(java.awt.event.ActionEvent)
- void btnVentasActionPerformed(java.awt.event.ActionEvent)
- void tableVentasMouseClicked(java.awt.event.MouseEvent)
- void btnPDFVentasActionPerformed(java.awt.event.ActionEvent)
- void btnGraficarActionPerformed(java.awt.event.ActionEvent)
- void jButton1ActionPerformed(java.awt.event.ActionEvent)
+ {static} void main(String[])
- void LimpiarCliente()
- void LimpiarProveedor()
- void LimpiarProductos()
- void TotalPagar()
- void LimpiarVenta()
- void RegistrarVenta()
- void RegistrarDetalle()
- void ActualizarStock()
- void LimpiarTableVenta()
- void LimpiarClienteVenta()
- void pdf()
}


Frames.JFrame <|-- Frames.Registro
Frames.JFrame <|-- Frames.Loging
Frames.JFrame <|-- Frames.Sistema
@enduml